use std::path::Path;

const ENV_KEYS: &[&str] = &[
    "GOOGLE_CLIENT_ID",
    "GOOGLE_CLIENT_SECRET",
    "MICROSOFT_CLIENT_ID",
    "MICROSOFT_CLIENT_SECRET",
    "PUSH_RELAY_URL",
];

fn main() {
    for key in ENV_KEYS {
        println!("cargo:rerun-if-env-changed={key}");
    }
    println!("cargo:rerun-if-changed=../.env");
    println!("cargo:rerun-if-changed=.env");

    load_dotenv();
    write_embedded_config();
    tauri_build::build()
}

fn load_dotenv() {
    for path in [".env", "../.env"] {
        if Path::new(path).exists() {
            if let Ok(content) = std::fs::read_to_string(path) {
                parse_dotenv(&content);
            }
            break;
        }
    }
}

fn parse_dotenv(content: &str) {
    for line in content.lines() {
        let line = line.trim();
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        if let Some((key, value)) = line.split_once('=') {
            let key = key.trim();
            if std::env::var(key).is_err() {
                std::env::set_var(key, value.trim().trim_matches('"'));
            }
        }
    }
}

fn write_embedded_config() {
    let out_dir = std::env::var("OUT_DIR").expect("OUT_DIR");
    let mut source = String::from(
        "// Generated by build.rs. Do not commit.\n\n\
         pub fn embedded_value(key: &str) -> Option<&'static str> {\n    match key {\n",
    );

    for key in ENV_KEYS {
        if let Ok(value) = std::env::var(key) {
            if !value.is_empty() {
                source.push_str(&format!("        {key:?} => Some({value:?}),\n"));
            }
        }
    }

    source.push_str("        _ => None,\n    }\n}\n");
    std::fs::write(format!("{out_dir}/embedded_config.rs"), source).expect("write embedded_config.rs");
}
